name: Go

on:
  push:
    branches: [ main ]

permissions: 
  contents: write
  packages: write

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.21

    - name: Check out code
      uses: actions/checkout@v4

    - name: Build
      run: go build -v -o supervisord_exporter ./...


    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions.
      with:
        files: |
          supervisord_exporter
        tag_name: ${{ github.ref }}